- name: Ensure Podman is installed
  dnf:
    name: podman
    state: present
  become: yes

- name: Ensure css-podman group exists
  group:
    name: css-podman
    state: present
  become: yes

- name: Ensure Podman base directory exists (on /data or /scratch depending on lab)
  file:
    path: "{{ podman_basedir }}"
    state: directory
    owner: root
    group: root
    mode: '1777'
  become: yes

- name: Get members of css-podman group
  command: getent group css-podman
  register: podman_group
  changed_when: false
  become: yes

- name: Extract css-podman users
  set_fact:
    podman_users: "{{ podman_group.stdout.split(':')[-1].split(',') | reject('equalto', '') | list }}"

- name: Create per-user podman-lab directory
  file:
    path: "{{ podman_basedir }}/{{ item }}/podman-lab"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0700'
  loop: "{{ podman_users }}"
  become: yes

- name: Create symlink ~/podman-lab for each user
  file:
    src: "{{ podman_basedir }}/{{ item }}/podman-lab"
    dest: "/home/{{ item }}/podman-lab"
    state: link
    owner: "{{ item }}"
  loop: "{{ podman_users }}"
  become: yes

- name: Ensure subuid ranges for css-podman users
  lineinfile:
    path: /etc/subuid
    regexp: "^{{ item }}:"
    line: "{{ item }}:{{ 100000 + (loop.index0 * 65536) }}:65536"
  loop: "{{ podman_users }}"
  become: yes

- name: Ensure subgid ranges for css-podman users
  lineinfile:
    path: /etc/subgid
    regexp: "^{{ item }}:"
    line: "{{ item }}:{{ 100000 + (loop.index0 * 65536) }}:65536"
  loop: "{{ podman_users }}"
  become: yes
