- name: Ensure Podman is installed
  dnf:
    name: podman
    state: present
  become: yes

- name: Set SELinux to permissive NOW (immediate, until reboot)
  command: setenforce 0
  become: yes
  ignore_errors: yes

- name: Make SELinux permissive permanently in /etc/selinux/config
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=.*'
    replace: 'SELINUX=permissive'
  become: yes

- name: Create /opt/podman directory
  file:
    path: /opt/podman
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Setup Podman Users, Directories, and Group
  import_tasks: setup-podman-users.yml
  become: yes

- name: Get members of css-podman group
  command: getent group css-podman
  register: podman_group
  changed_when: false
  become: yes

- name: Extract css-podman users
  set_fact:
    podman_users: "{{ podman_group.stdout.split(':')[-1].split(',') | reject('equalto', '') | list }}"

- name: Ensure subuid ranges for css-podman users
  lineinfile:
    path: /etc/subuid
    regexp: "^{{ item }}:"
    line: "{{ item }}:{{ 100000 + (idx * 65536) }}:65536"
  loop: "{{ podman_users }}"
  loop_control:
    label: "{{ item }}"
  become: yes

- name: Ensure subgid ranges for css-podman users
  lineinfile:
    path: /etc/subgid
    regexp: "^{{ item }}:"
    line: "{{ item }}:{{ 100000 + (loop.index0 * 65536) }}:65536"
  loop: "{{ podman_users }}"
  loop_control:
    label: "{{ item }}"
  become: yes
