---
- name: Ensure css-podman group exists
  group:
    name: css-podman
    state: present

- name: Ensure /podman directory exists with correct permissions
  file:
    path: /podman
    state: directory
    owner: root
    group: root
    mode: '1777'
